version: '3.7'

networks:
  default:
  localstack-net:
    external: true

services:
  server.core:
    networks:
      - localstack-net
    env_file:
      - docker-compose.env

  api.core:
    networks:
      - localstack-net
    env_file:
      - docker-compose.env
  