version: '3.7'

services:
  server.core:
    image: ${DOCKER_REGISTRY-}server.core
    build:
      context: .
      dockerfile: src/Server.Core/Dockerfile

  api.core:
    image: ${DOCKER_REGISTRY-}api.core
    build:
      context: .
      dockerfile: src/Api.Core/Dockerfile
    ports:
      - "8000:80"